# CircleCI configuration for Spectrum

# Aliases
aliases:

  # Cache Management
  - &restore-yarn-cache
    keys:
      - v1-yarn-{{ arch }}-{{ checksum "package.json" }}
      - v1-yarn-{{ arch }}-

  - &save-yarn-cache
    paths:
      - node_modules
      - mobile/node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ arch }}-{{ checksum "package.json" }}

  - &yarn
    |
      yarn
      cd ./mobile && yarn && yarn setup

defaults: &defaults
  working_directory: ~/spectrum

js_defaults: &js_defaults
  <<: *defaults
  docker:
    - image: circleci/node:8

rethinkdb: &rethinkdb
  <<: *js_defaults
  steps:
    - run: source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
    - run: wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    - run: sudo apt-get update
    - run: sudo apt-get install rethinkdb=2.3.5
    - run:
      - command: rethinkdb --bind all
      - background: true

servers: &servers
  <<: *rethinkdb
  steps:
      - run: node -e "const setup = require('./shared/testing/setup.js')().then(() => process.exit())"
      - run: yarn run build:web
      - run: yarn run build:iris
      - run:
        - command: TEST_DB=true yarn run dev:iris
        - background: true
      - run:
        - command: yarn run dev:web
        - background: true
      # This is about how long it takes our servers to start
      - run: sleep 60

macos_defaults: &macos_defaults
  <<: *defaults
  macos:
    xcode: "9.2.0"

version: 2
jobs:

  # Set up environment and install required dependencies
  checkout_environment:
    <<: *js_defaults
    steps:
      - checkout

      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

      - persist_to_workspace:
          root: .
          paths: .

  # Tests js of the mobile app
  test_mobile_js:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run: cd ./mobile && yarn test:unit

  test_js:
    <<: *servers
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run: yarn run flow
      - run: yarn run test:ci


  # Tests native code of the mobile app
  test_mobile_native:
    <<: *macos_defaults
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run:
          name: Install Expo CLI
          command: npm install -g exp
      - run:
          name: Install Detox dependencies
          command: |
            brew tap wix/brew
            brew install applesimutils --HEAD
            npm install -g detox-cli
      - run:
          name: Rebuild Detox frameworks
          command: |
            cd ./mobile
            detox clean-framework-cache
            detox build-framework-cache
      - run:
          name: Start Packager in the background
          command: cd ./mobile && exp start
          background: true
      - run: cd ./mobile && yarn test:e2e

workflows:
  version: 2

  # Tests mobile app
  test_mobile:
    jobs:
      - checkout_environment
      - test_mobile_js:
          requires:
            - checkout_environment
      # Disabled as Expo is fixing their critical issue with Detox
      # - test_mobile_native:
      #     requires:
      #       - checkout_environment

  test_web:
    jobs:
      - checkout_environment
      - test_js:
        requires:
          - checkout_environment
