version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/spectrum
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - spectrum-{{ .Branch }}-{{ checksum "package.json" }}
            - spectrum-{{ .Branch }}
            
      # Install mobile dependencies and Expo client locally
      - run: cd ./mobile && yarn && yarn setup
      
      - save_cache:
          key: spectrum-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - ~/spectrum/mobile/node_modules
            
      - run: npm test
